// Posts
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';

// Sponsors
export const REQUEST_SPONSOR_LEVELS = 'REQUEST_SPONSOR_LEVELS';
export const RECEIVE_SPONSOR_LEVELS = 'RECEIVE_SPONSOR_LEVELS';
export const REQUEST_SPONSORS = 'REQUEST_SPONSORS';
export const RECEIVE_SPONSORS = 'RECEIVE_SPONSORS';

// Speakers
export const REQUEST_SPEAKERS = 'REQUEST_SPEAKERS';
export const RECEIVE_SPEAKERS = 'RECEIVE_SPEAKERS';

// Sessions
export const REQUEST_SESSIONS = 'REQUEST_SESSIONS';
export const RECEIVE_SESSIONS = 'RECEIVE_SESSIONS';
